pipeline:
    build:
      image: java:openjdk-8
      environment:
        - GRADLE_USER_HOME=~/.gradle
      commands:
        # install ant build tool
        - apt-get install ant

        # install maven build tool
        - wget http://mirrors.viethosting.com/apache/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz
        - tar xzvf apache-maven-3.5.0-bin.tar.gz
        - cd apache-maven-3.5.0/bin && export PATH=$PATH:$(pwd) && cd -

        # install framgia ci tool
        - curl -o /usr/bin/framgia-ci https://raw.githubusercontent.com/framgia/ci-report-tool/master/dist/framgia-ci && chmod +x /usr/bin/framgia-ci
        - framgia-ci run
